export const Top100Languages = [
  'English',
  'Mandarin Chinese',
  'Hindi',
  'Spanish',
  'French',
  'Modern Standard Arabic',
  'Bengali',
  'Russian',
  'Portuguese',
  'Urdu',
  'Indonesian',
  'German',
  'Japanese',
  'Nigerian Pidgin',
  'Egyptian Arabic',
  'Marathi',
  'Telugu',
  'Turkish',
  'Tamil',
  'Cantonese (Yue Chinese)',
  'Vietnamese',
  'Wu Chinese',
  'Tagalog',
  'Korean',
  'Farsi (Iranian Persian)',
  'Javanese',
  'Italian',
  'Thai',
  'Gujarati',
  'Levantine Arabic',
  'Amharic',
  'Kannada',
  'Bhojpuri',
  'Sudanese Arabic',
  'Western Punjabi',
  'Hausa',
  'Oriya (Odia)',
  'Malayalam',
  'Eastern Punjabi',
  'Sunda',
  'Romanian',
  'Burmese',
  'Northern Uzbek',
  'Serbo-Croatian',
  'Assamese',
  'Nepali',
  'Northern Pashto',
  'Swahili',
  'Magahi',
  'Awadhi',
  'Maithili',
  'Yoruba',
  'Malagasy',
  'Sinalese',
  'Hakka Chinese',
  'Azerbaijani',
  'Haryanvi',
  'Min Nan Chinese',
  'Somali',
  'Northern Zhuang',
  'Hungarian',
  'Sinhala',
  'Chittagonian',
  'Cebuano',
  'Kurdish (Kurmanji)',
  'Marwari',
  'Kazakh',
  'Khmer (Central)',
  'Fula (Nigerian Fulfulde)',
  'Zhuang',
  'Napoletano-Calabrese',
  'Haitian Creole French',
  'Chhattisgarhi',
  'Min Bei Chinese',
  'Belarusan',
  'Deccan',
  'Bulgarian',
  'Swiss German',
  'Chewa',
  'Oromo',
  'Macedonian',
  'Kinyarwanda',
  'Quechua',
  'Xhosa',
  'Shona',
  'Zaza',
  'Tigrinya',
  'Ilokano',
  'Tatar',
  'Uyghur',
  'Sindhi',
  'Lombard',
  'Ilocano',
  'Nepali (Central)',
  'Azerbaijani (North)',
  'Madura',
  'Pashto (Southern)',
  'Cebuano (Bisayan)',
  'Gikuyu',
  'Yakan',
  'Balochi (Southern)',
  'Cantonese Chinese',
] as const;
